plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${mc_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation "me.zeroeightsix:fiber:0.23.0-2"
    include "me.zeroeightsix:fiber:0.23.0-2"
}

loom {
    def aw = project(':Xplat').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
        }
        server {
            server()
            setConfigName('Fabric Server')
        }
        configureEach {
            runDir "../run"
            ideConfigGenerated(true)
        }
    }
}

sourceSets.main.resources { srcDir project(":Xplat").file('src/main/generated/').getAbsolutePath() }

publishing {
    publications {
        maven(MavenPublication) {
            group "com.mosaicmodding"
            artifactId project.mod_id + "-fabric"
            version project.mod_version
            from components.java
        }
    }
    repositories {
        maven {
            name = "Mosaic-Modding-Maven"
            url = "https://maven.mosaicmodding.com"

            credentials(HttpHeaderCredentials) {
                name = "X-Custom-Auth-Key"
                value = System.getenv("AUTH_KEY_SECRET")
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}
