plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':Xplat').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            gameDirectory = file('../run')
        }
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('../Xplat/src/main/generated/').getAbsolutePath(), '--existing', file('../Xplat/src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }
    mods {
        "${mod_id}" {
            sourceSet project.sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir project(":Xplat").file('src/main/generated/').getAbsolutePath() }

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            group "com.mosaicmodding"
            artifactId project.mod_id + "-forge"
            version project.mod_version
            from components.java
        }
    }
    repositories {
        maven {
            name = "Mosaic-Modding-Maven"
            url = "https://maven.mosaicmodding.com"

            credentials(HttpHeaderCredentials) {
                name = "X-Custom-Auth-Key"
                value = System.getenv("AUTH_KEY_SECRET")
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}
