name: Deploy to Maven

# to automate this further we could later automatically increase the mod version perhaps

on: push

jobs:
  build-and-deploy:
    if: startsWith(github.ref, 'refs/tags/') #only run if the commit pushes a tag
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (default branch)
      - name: Checkout code
        uses: actions/checkout@v4

      # Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up environment variables
      - name: Set environment variables
        run: echo "AUTH_KEY_SECRET=${{ secrets.AUTH_KEY_SECRET }}" >> $GITHUB_ENV

      # Build and publish Forge
      - name: Build and publish Forge
        run: ./gradlew :forge:publish

      # Build and publish Fabric
      - name: Build and publish Fabric
        run: ./gradlew :fabric:publish