name: Deploy to Maven

# to automate this further we could later automatically increase the mod version perhaps

on: push

jobs:
  build-and-deploy:
    if: startsWith(github.ref, 'refs/tags/') #only run if the commit pushes a tag
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (default branch)
      - name: Checkout code
        uses: actions/checkout@v4

      # Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Calculate artifact names
        id: calculate_artifact_names
        run: |
          MC=$(awk -F '=' '/mc_version/ { print $2; }' gradle.properties)
          VERSION=$(awk -F '=' '/mod_version/ { print $2; }' gradle.properties)
          echo "forge=forge/build/libs/MosaicCosmetics-${MC}-${VERSION}-forge.jar" >> "$GITHUB_OUTPUT"
          echo "fabric=Fabric/build/libs/MosaicCosmetics-${MC}-${VERSION}-fabric.jar" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ steps.calculate_artifact_names.outputs.fabric }}
            ${{ steps.calculate_artifact_names.outputs.forge }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Set up environment variables
      - name: Set environment variables
        run: echo "AUTH_KEY_SECRET=${{ secrets.AUTH_KEY_SECRET }}" >> $GITHUB_ENV

      # Build and publish Forge to maven
      - name: Build and publish Forge
        run: ./gradlew :forge:publish

      # Build and publish Fabric to maven
      - name: Build and publish Fabric
        run: ./gradlew :fabric:publish
